######################################################################
# Automatically generated by qmake (2.01a) Fri Feb 4 19:21:19 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cannonbarreldlg.h cannonfield.h
FORMS += cannonbarreldlg.ui
SOURCES += cannonbarreldlg.cpp cannonfield.cpp main.cpp

QT += network
